name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]  # or whichever branch you want to trigger on

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      # Enable QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the image
      - name: Build and push
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t mutumamunyua/crophealthai:latest \
            --push .

      # Trigger CD on Render
      - name: Trigger Render Redeploy
        run: |
          echo "Triggering redeploy on Render..."
          curl -X POST ${{ secrets.RENDER_WEBHOOK_URL }}